package de.joshuaw.mmatechniques;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.List;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@Setter
@DynamoDBTable(tableName = "Techniques")
public class Technique {
  private String title;
  private String id;
  private String description;
  private List<String> videoLinks;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getTitle() {
    return title;
  }

  @DynamoDBAttribute
  public String getDescription() {
    return description;
  }

  @DynamoDBAttribute
  public List<String> getVideoLinks() {
    return videoLinks;
  }

  public Technique(final String title) {
    this.title = title;
  }
}
